name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Verify Gradle Wrapper
        run: |
          cd app
          if [ ! -f "gradlew" ]; then
            echo "gradlew not found! Generating..."
            ./gradlew wrapper --gradle-version 8.7
          fi
          chmod +x gradlew
      
      - name: Build with Gradle
        run: |
          cd app
          ./gradlew build
      
      - name: Run tests with coverage
        run: |
          cd app
          ./gradlew jacocoTestReport
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./app/build/reports/jacoco/test/jacocoTestReport.xml